### ISSUE TITLE
xdebug port

### ISSUE THREAD

**Issue by agarzon** [linuxjuggler/php-7.1-xdebug-alpine#1]
Hi.

You cannot use port 9000 for xdebug.remote_port since is already been used by PHP-FPM service.

It is a well know problem: https://www.theaveragedev.com/xdebug-and-php-fpm-configuration/

I suggest to you change the xdebug.remote_port to something like 9100 and add the note into the readme.

Regards.

**Comment by zaherg** [comment]
@agarzon I didn't face any problem using it, did you face any problem?

anyway, I'll try again, and sorry for not answering your comment earlier

**Comment by zaherg** [comment]
@agarzon I  rechecked and tested the debug, and I cant seems to face any problem. as you can see in the image I didn't change the port and phpstorm is connecting to xdebug on port 9000 as normal.

![working-xdebug](https://user-images.githubusercontent.com/27624/33677781-f35cf512-daca-11e7-99da-1869eb67f756.png)
